In [104]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [62]:
wine = datasets.load_wine()

In [63]:
print(wine.feature_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [64]:
print(wine.data[0:5])

[[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]]


In [65]:
print(wine.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [66]:
print(len(wine.target))

178


In [67]:
print(wine.data.shape)

(178, 13)


In [68]:
indices = np.arange(len(wine.data))

In [73]:
x_train, x_test, y_train, y_test,train_indices, test_indices = train_test_split(wine.data, wine.target,indices, test_size=0.3, random_state=0)
print(y_train)

[0 1 2 2 1 2 2 0 1 2 1 1 2 1 0 1 1 1 0 0 1 1 2 2 1 1 1 2 2 0 2 1 1 1 1 1 0
 0 1 0 2 0 2 0 0 1 0 1 1 0 2 1 0 1 1 1 2 0 2 2 0 0 1 2 0 0 1 1 0 0 0 2 1 0
 1 2 0 1 2 2 0 0 2 0 2 1 0 0 1 0 2 1 2 0 2 2 2 0 1 1 1 1 2 2 1 1 0 1 2 2 0
 0 2 1 1 1 0 0 0 1 1 1 0 2]


In [74]:
print("train_data_indices: ",train_indices)

train_data_indices:  [ 22 108 175 145  71 162 156  27  83 134  97 118 163  62   2  59  95  96
  43  10 109  73 171 159 110 125 116 166 170  50 155  89  64 122 124  69
  49  48  85  13 136  23 165  20  15  78  52 100  76   3 176 107   6  68
  75  84 130  12 137 152  14   0  91 153  46  11 119 102  35  57  41 173
  65   1 120 143  42 105 132 154  17  38 133  53 139 128  34  28 114  31
 149 127 157  32 142 150 147  29  99  82  79 115 148 177  72  77  25  81
 167 169  39  58 140  88  70  87  36  21   9 103  67 117  47 172]


In [75]:
print("test_data_indices: ",test_indices)

test_data_indices:  [ 54 151  63  55 123 121   7 160 106  90 141 146   5  98 168  80  33  18
  61  51  66  37   4 104  60 111 126  86 112 164  26  56 129  45   8  44
 161  92  94 174  24  30  93 101 113  19 135  74 144  16 131 138  40 158]


In [76]:
x_train, x_test, y_train, y_test, train_indices, test_indices = train_test_split(wine.data, wine.target,indices, test_size=0.2, random_state=0)
print(y_train)

[2 1 1 2 0 0 1 1 1 0 2 1 2 0 2 2 0 2 0 1 2 2 1 2 2 0 1 2 1 1 2 1 0 1 1 1 0
 0 1 1 2 2 1 1 1 2 2 0 2 1 1 1 1 1 0 0 1 0 2 0 2 0 0 1 0 1 1 0 2 1 0 1 1 1
 2 0 2 2 0 0 1 2 0 0 1 1 0 0 0 2 1 0 1 2 0 1 2 2 0 0 2 0 2 1 0 0 1 0 2 1 2
 0 2 2 2 0 1 1 1 1 2 2 1 1 0 1 2 2 0 0 2 1 1 1 0 0 0 1 1 1 0 2]


In [77]:
print("train_data_indices: ",train_indices)

train_data_indices:  [161  92  94 174  24  30  93 101 113  19 135  74 144  16 131 138  40 158
  22 108 175 145  71 162 156  27  83 134  97 118 163  62   2  59  95  96
  43  10 109  73 171 159 110 125 116 166 170  50 155  89  64 122 124  69
  49  48  85  13 136  23 165  20  15  78  52 100  76   3 176 107   6  68
  75  84 130  12 137 152  14   0  91 153  46  11 119 102  35  57  41 173
  65   1 120 143  42 105 132 154  17  38 133  53 139 128  34  28 114  31
 149 127 157  32 142 150 147  29  99  82  79 115 148 177  72  77  25  81
 167 169  39  58 140  88  70  87  36  21   9 103  67 117  47 172]


In [78]:
print("test_data_indices: ",test_indices)

test_data_indices:  [ 54 151  63  55 123 121   7 160 106  90 141 146   5  98 168  80  33  18
  61  51  66  37   4 104  60 111 126  86 112 164  26  56 129  45   8  44]


In [79]:
x_train, x_test, y_train, y_test, train_indices, test_indices = train_test_split(wine.data, wine.target,indices, test_size=0.3, random_state=2)
print(y_train)

[1 2 2 0 1 2 1 2 2 0 2 0 2 1 1 0 0 2 1 1 0 2 2 1 1 0 2 0 1 2 2 2 1 2 2 0 0
 0 1 1 2 1 2 1 2 1 1 1 0 1 2 1 1 1 2 1 0 1 0 0 2 1 1 1 0 1 0 0 0 1 0 1 0 0
 2 1 1 1 1 1 1 2 2 0 0 2 2 0 0 1 2 1 2 0 1 1 1 2 0 0 0 1 0 1 0 1 0 1 1 2 0
 1 0 2 1 2 0 1 1 0 0 1 0 2]


In [80]:
print("train_data_indices: ",train_indices)

train_data_indices:  [ 99 131 159  57  71 170 118 141 147  11 167  36 152 115  62   0  27 138
 111  98  20 139 137 126  77  30 135  17  59 160 146 140 108 143 155  21
  55  16  91 100 175  74 142 128 174  87  90  84  18  97 134 125  61  81
 145  68   1  82  56  19 161  86  70 101   9  60  34  40  10  76   8 114
  26  32 173  96  83 110 105  73 117 176 136  39  49 165 132  50  52  80
 164 121 177  46  88  69  67 169  58  33  38 103  51 107   4 102  37 116
 124 148  31  63  47 172  95 162   7 104  75  43  22  72  15 168]


In [81]:
print("test_data_indices: ",test_indices)

test_data_indices:  [ 12  23 166  25  35  13  65 171 112  48  78   3   6 158 149 122  42   2
  29 157 130  45 106  94   5  53  93  41  54  24 133  64 151 153  28 113
 154 120  89  92 156 144  79  14 163 119 129  44 150  66 123 127 109  85]


In [82]:
x_train, x_test, y_train, y_test, train_indices, test_indices = train_test_split(wine.data, wine.target,indices, test_size=0.3, random_state=3)
print(y_train)

[1 1 1 1 0 2 0 1 0 0 2 2 2 1 2 2 1 0 0 1 0 1 1 0 2 1 1 1 1 0 0 2 2 2 0 2 1
 0 0 0 2 1 2 2 1 1 0 2 0 2 2 0 2 1 0 0 2 0 1 1 0 1 2 1 1 0 1 0 1 1 1 1 2 1
 2 1 1 0 1 2 1 0 2 0 2 0 1 0 1 0 0 1 1 0 0 1 2 1 1 1 1 1 1 1 0 1 2 1 0 2 1
 2 2 1 2 2 2 1 2 0 0 2 2 1]


In [83]:
print("train_data_indices: ",train_indices)

train_data_indices:  [126 101  86  87  57 165  43 103  22  17 168 143 153  63 134 175 105  45
  35  65  50  92 118  19 145 125  68  76 120  10  11 156 157 160   9 146
 128  29  39  56 173 122 137 140  59 108  44 155  36 139 158  52 133  61
  48  30 144  13  95  96  55  75 135 114 121  32  80  16  91  99 100 124
 171  74 170 117  85   1 113 172 116  18 174  54 167  28 127  49  94  20
  37  79 123  33   7  62 177  97 110 104  69  90 129  60   2  66 150  81
  26 142  93 148 166 119 149 138 169 107 147  21   0 131 152 106]


In [84]:
print("test_data_indices: ",test_indices)

test_data_indices:  [ 40  53  34 109 159  23  46  72  78  38  64   3  82  70  51   6  84  15
 154 163  58 136  25 176  71 115  47  41  89  83 112   4 132  98 111 130
  42  67  31 141   5 162  88 102  77  12  14  24 151  73   8 164  27 161]


In [124]:
model = KNeighborsClassifier(n_neighbors = 14)

model.fit(x_train,y_train)

predicted = model.predict(x_test)    

print(predicted)

[2 0 0 2 2 0 0 1 2 0 1 0 2 0 0 0 1 0 2 2 0 2 0 0 1 1 0 0 2 1 2 2 2 2 1 2 0
 1 0 2 0 2 2 1 2 0 0 0 1 0 0 2 0 2]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [125]:
print(model.score(x_test, y_test))

0.7407407407407407


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [126]:
m = classification_report(y_test, predicted, target_names = wine.target_names)
print(m)

              precision    recall  f1-score   support

     class_0       0.88      0.91      0.89        23
     class_1       0.90      0.47      0.62        19
     class_2       0.50      0.83      0.62        12

    accuracy                           0.74        54
   macro avg       0.76      0.74      0.71        54
weighted avg       0.80      0.74      0.74        54



In [127]:
cm = confusion_matrix(y_test, predicted)
print(cm)

[[21  0  2]
 [ 2  9  8]
 [ 1  1 10]]


In [31]:
# le = preprocessing.LabelEncoder()


# weather_encoded = le.fit_transform(weather)    #converting string labels into numeric values
# temp_encoded = le.fit_transform(temp)    #converting string labels into numeric values
# play_encoded = le.fit_transform(play)    #converting string labels into numeric values

# print(weather_encoded)

In [32]:
# print(temp_encoded)

In [33]:
# print(play_encoded)

In [34]:
# features = list(zip(weather_encoded, temp_encoded))  #Zipping 2 columns in one varieble
# features