In [42]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier

In [45]:
df = pd.read_csv("knn_temp.csv")

In [46]:
df

weather  temp play
0      sunny   hot   no
1      sunny   hot   no
2   overcast   hot  yes
3      rainy  mild  yes
4      rainy  cool  yes
5      rainy  cool   no
6   overcast  cool  yes
7      sunny  mild   no
8      sunny  cool  yes
9      rainy  mild  yes
10     sunny  mild  yes
11  overcast  mild  yes
12  overcast   hot  yes
13     rainy  mild   no

In [47]:
weather = list(df['weather'])
temp = list(df['temp'])
play = list(df['play'])

In [48]:
type(weather)

list

In [49]:
df.columns

Index(['weather', 'temp', 'play'], dtype='object')

In [50]:
le = preprocessing.LabelEncoder()


weather_encoded = le.fit_transform(weather)    #converting string labels into numeric values
temp_encoded = le.fit_transform(temp)    #converting string labels into numeric values
play_encoded = le.fit_transform(play)    #converting string labels into numeric values

print(weather_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [51]:
print(temp_encoded)

[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [52]:
print(play_encoded)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [53]:
features = list(zip(weather_encoded, temp_encoded))  #Zipping 2 columns in one varieble
features

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [55]:
model = KNeighborsClassifier(n_neighbors = 3)

model.fit(features,play)

predicted = model.predict([[0,2]])    #0:overcast, 2:mild

print(predicted)

['yes']


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
